<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter.proto

namespace Protos\Metadata;

class Filter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
«
filter.protoacs.tablestore.filter"I
Filter/
type (2!.acs.tablestore.filter.FilterType
filter ("Œ
CompositeColumnValueFilter:

combinator (2&.acs.tablestore.filter.LogicalOperator2
sub_filters (2.acs.tablestore.filter.Filter"·
SingleColumnValueFilter9

comparator (2%.acs.tablestore.filter.ComparatorType
column_name (	
column_value (
filter_if_missing (
latest_version_only ("7
ColumnPaginationFilter
offset (
limit (*a

FilterType
FT_SINGLE_COLUMN_VALUE
FT_COMPOSITE_COLUMN_VALUE
FT_COLUMN_PAGINATION*4
LogicalOperator

LO_NOT

LO_AND	
LO_OR*€
ComparatorType
CT_EQUAL
CT_NOT_EQUAL
CT_GREATER_THAN
CT_GREATER_EQUAL
CT_LESS_THAN
CT_LESS_EQUALBÊProtosâProtos\\Metadata'
        , true);

        static::$is_initialized = true;
    }
}

