<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tablestore.proto

namespace Protos\Metadata;

class Tablestore
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
”
tablestore.protoacs.tablestore"&
Error
code (	
message (	"+
CapacityUnit
read (
write (BÊProtosâProtos\\Metadata'
        , true);

        static::$is_initialized = true;
    }
}

