<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/tablestore/row_single.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.row.single.CapacityUnit</code>
 */
class CapacityUnit extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 read = 1;</code>
     */
    protected $read = null;
    /**
     * Generated from protobuf field <code>optional int32 write = 2;</code>
     */
    protected $write = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $read
     *     @type int $write
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\RowSingle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 read = 1;</code>
     * @return int
     */
    public function getRead()
    {
        return isset($this->read) ? $this->read : 0;
    }

    public function hasRead()
    {
        return isset($this->read);
    }

    public function clearRead()
    {
        unset($this->read);
    }

    /**
     * Generated from protobuf field <code>optional int32 read = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRead($var)
    {
        GPBUtil::checkInt32($var);
        $this->read = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 write = 2;</code>
     * @return int
     */
    public function getWrite()
    {
        return isset($this->write) ? $this->write : 0;
    }

    public function hasWrite()
    {
        return isset($this->write);
    }

    public function clearWrite()
    {
        unset($this->write);
    }

    /**
     * Generated from protobuf field <code>optional int32 write = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWrite($var)
    {
        GPBUtil::checkInt32($var);
        $this->write = $var;

        return $this;
    }

}

