<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.filter.ColumnPaginationFilter</code>
 */
class ColumnPaginationFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required int32 offset = 1;</code>
     */
    protected $offset = null;
    /**
     * Generated from protobuf field <code>required int32 limit = 2;</code>
     */
    protected $limit = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $offset
     *     @type int $limit
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\Filter::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required int32 offset = 1;</code>
     * @return int
     */
    public function getOffset()
    {
        return isset($this->offset) ? $this->offset : 0;
    }

    public function hasOffset()
    {
        return isset($this->offset);
    }

    public function clearOffset()
    {
        unset($this->offset);
    }

    /**
     * Generated from protobuf field <code>required int32 offset = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>required int32 limit = 2;</code>
     * @return int
     */
    public function getLimit()
    {
        return isset($this->limit) ? $this->limit : 0;
    }

    public function hasLimit()
    {
        return isset($this->limit);
    }

    public function clearLimit()
    {
        unset($this->limit);
    }

    /**
     * Generated from protobuf field <code>required int32 limit = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

}

