<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.filter.CompositeColumnValueFilter</code>
 */
class CompositeColumnValueFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required .acs.tablestore.filter.LogicalOperator combinator = 1;</code>
     */
    protected $combinator = null;
    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.filter.Filter sub_filters = 2;</code>
     */
    private $sub_filters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $combinator
     *     @type array<\Protos\Filter>|\Google\Protobuf\Internal\RepeatedField $sub_filters
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\Filter::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.filter.LogicalOperator combinator = 1;</code>
     * @return int
     */
    public function getCombinator()
    {
        return isset($this->combinator) ? $this->combinator : 0;
    }

    public function hasCombinator()
    {
        return isset($this->combinator);
    }

    public function clearCombinator()
    {
        unset($this->combinator);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.filter.LogicalOperator combinator = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCombinator($var)
    {
        GPBUtil::checkEnum($var, \Protos\LogicalOperator::class);
        $this->combinator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.filter.Filter sub_filters = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubFilters()
    {
        return $this->sub_filters;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.filter.Filter sub_filters = 2;</code>
     * @param array<\Protos\Filter>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubFilters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Filter::class);
        $this->sub_filters = $arr;

        return $this;
    }

}

