<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use UnexpectedValueException;

/**
 * Protobuf type <code>acs.tablestore.table.DefinedColumnType</code>
 */
class DefinedColumnType
{
    /**
     * Generated from protobuf enum <code>DCT_INTEGER = 1;</code>
     */
    const DCT_INTEGER = 1;
    /**
     * Generated from protobuf enum <code>DCT_DOUBLE = 2;</code>
     */
    const DCT_DOUBLE = 2;
    /**
     * Generated from protobuf enum <code>DCT_BOOLEAN = 3;</code>
     */
    const DCT_BOOLEAN = 3;
    /**
     * Generated from protobuf enum <code>DCT_STRING = 4;</code>
     */
    const DCT_STRING = 4;
    /**
     * Generated from protobuf enum <code>DCT_BLOB = 7;</code>
     */
    const DCT_BLOB = 7;

    private static $valueToName = [
        self::DCT_INTEGER => 'DCT_INTEGER',
        self::DCT_DOUBLE => 'DCT_DOUBLE',
        self::DCT_BOOLEAN => 'DCT_BOOLEAN',
        self::DCT_STRING => 'DCT_STRING',
        self::DCT_BLOB => 'DCT_BLOB',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

