<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter.proto

namespace Protos;

use UnexpectedValueException;

/**
 * Protobuf type <code>acs.tablestore.filter.FilterType</code>
 */
class FilterType
{
    /**
     * Generated from protobuf enum <code>FT_SINGLE_COLUMN_VALUE = 1;</code>
     */
    const FT_SINGLE_COLUMN_VALUE = 1;
    /**
     * Generated from protobuf enum <code>FT_COMPOSITE_COLUMN_VALUE = 2;</code>
     */
    const FT_COMPOSITE_COLUMN_VALUE = 2;
    /**
     * Generated from protobuf enum <code>FT_COLUMN_PAGINATION = 3;</code>
     */
    const FT_COLUMN_PAGINATION = 3;

    private static $valueToName = [
        self::FT_SINGLE_COLUMN_VALUE => 'FT_SINGLE_COLUMN_VALUE',
        self::FT_COMPOSITE_COLUMN_VALUE => 'FT_COMPOSITE_COLUMN_VALUE',
        self::FT_COLUMN_PAGINATION => 'FT_COLUMN_PAGINATION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

