<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/tablestore/row_single.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.row.single.GetRowRequest</code>
 */
class GetRowRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     */
    protected $table_name = null;
    /**
     * Generated from protobuf field <code>required bytes primary_key = 2;</code>
     */
    protected $primary_key = null;
    /**
     * Generated from protobuf field <code>repeated string columns_to_get = 3;</code>
     */
    private $columns_to_get;
    /**
     * Generated from protobuf field <code>optional .acs.tablestore.row.single.TimeRange time_range = 4;</code>
     */
    protected $time_range = null;
    /**
     * Generated from protobuf field <code>optional int32 max_versions = 5;</code>
     */
    protected $max_versions = null;
    /**
     * Generated from protobuf field <code>optional bytes filter = 7;</code>
     */
    protected $filter = null;
    /**
     * Generated from protobuf field <code>optional string start_column = 8;</code>
     */
    protected $start_column = null;
    /**
     * Generated from protobuf field <code>optional string end_column = 9;</code>
     */
    protected $end_column = null;
    /**
     * Generated from protobuf field <code>optional bytes token = 10;</code>
     */
    protected $token = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $table_name
     *     @type string $primary_key
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $columns_to_get
     *     @type \Protos\TimeRange $time_range
     *     @type int $max_versions
     *     @type string $filter
     *     @type string $start_column
     *     @type string $end_column
     *     @type string $token
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\RowSingle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return isset($this->table_name) ? $this->table_name : '';
    }

    public function hasTableName()
    {
        return isset($this->table_name);
    }

    public function clearTableName()
    {
        unset($this->table_name);
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>required bytes primary_key = 2;</code>
     * @return string
     */
    public function getPrimaryKey()
    {
        return isset($this->primary_key) ? $this->primary_key : '';
    }

    public function hasPrimaryKey()
    {
        return isset($this->primary_key);
    }

    public function clearPrimaryKey()
    {
        unset($this->primary_key);
    }

    /**
     * Generated from protobuf field <code>required bytes primary_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPrimaryKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->primary_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string columns_to_get = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumnsToGet()
    {
        return $this->columns_to_get;
    }

    /**
     * Generated from protobuf field <code>repeated string columns_to_get = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumnsToGet($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->columns_to_get = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.row.single.TimeRange time_range = 4;</code>
     * @return \Protos\TimeRange|null
     */
    public function getTimeRange()
    {
        return $this->time_range;
    }

    public function hasTimeRange()
    {
        return isset($this->time_range);
    }

    public function clearTimeRange()
    {
        unset($this->time_range);
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.row.single.TimeRange time_range = 4;</code>
     * @param \Protos\TimeRange $var
     * @return $this
     */
    public function setTimeRange($var)
    {
        GPBUtil::checkMessage($var, \Protos\TimeRange::class);
        $this->time_range = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 max_versions = 5;</code>
     * @return int
     */
    public function getMaxVersions()
    {
        return isset($this->max_versions) ? $this->max_versions : 0;
    }

    public function hasMaxVersions()
    {
        return isset($this->max_versions);
    }

    public function clearMaxVersions()
    {
        unset($this->max_versions);
    }

    /**
     * Generated from protobuf field <code>optional int32 max_versions = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxVersions($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_versions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes filter = 7;</code>
     * @return string
     */
    public function getFilter()
    {
        return isset($this->filter) ? $this->filter : '';
    }

    public function hasFilter()
    {
        return isset($this->filter);
    }

    public function clearFilter()
    {
        unset($this->filter);
    }

    /**
     * Generated from protobuf field <code>optional bytes filter = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, False);
        $this->filter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string start_column = 8;</code>
     * @return string
     */
    public function getStartColumn()
    {
        return isset($this->start_column) ? $this->start_column : '';
    }

    public function hasStartColumn()
    {
        return isset($this->start_column);
    }

    public function clearStartColumn()
    {
        unset($this->start_column);
    }

    /**
     * Generated from protobuf field <code>optional string start_column = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setStartColumn($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_column = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string end_column = 9;</code>
     * @return string
     */
    public function getEndColumn()
    {
        return isset($this->end_column) ? $this->end_column : '';
    }

    public function hasEndColumn()
    {
        return isset($this->end_column);
    }

    public function clearEndColumn()
    {
        unset($this->end_column);
    }

    /**
     * Generated from protobuf field <code>optional string end_column = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setEndColumn($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_column = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes token = 10;</code>
     * @return string
     */
    public function getToken()
    {
        return isset($this->token) ? $this->token : '';
    }

    public function hasToken()
    {
        return isset($this->token);
    }

    public function clearToken()
    {
        unset($this->token);
    }

    /**
     * Generated from protobuf field <code>optional bytes token = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->token = $var;

        return $this;
    }

}

