<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use UnexpectedValueException;

/**
 * Protobuf type <code>acs.tablestore.table.IndexType</code>
 */
class IndexType
{
    /**
     * Generated from protobuf enum <code>IT_GLOBAL_INDEX = 0;</code>
     */
    const IT_GLOBAL_INDEX = 0;
    /**
     * Generated from protobuf enum <code>IT_LOCAL_INDEX = 1;</code>
     */
    const IT_LOCAL_INDEX = 1;

    private static $valueToName = [
        self::IT_GLOBAL_INDEX => 'IT_GLOBAL_INDEX',
        self::IT_LOCAL_INDEX => 'IT_LOCAL_INDEX',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

