<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.table.IndexMeta</code>
 */
class IndexMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required string name = 1;</code>
     */
    protected $name = null;
    /**
     * Generated from protobuf field <code>repeated string primary_key = 2;</code>
     */
    private $primary_key;
    /**
     * Generated from protobuf field <code>repeated string defined_column = 3;</code>
     */
    private $defined_column;
    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.IndexUpdateMode index_update_mode = 4;</code>
     */
    protected $index_update_mode = null;
    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.IndexType index_type = 5;</code>
     */
    protected $index_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $primary_key
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $defined_column
     *     @type int $index_update_mode
     *     @type int $index_type
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\Table::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>required string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string primary_key = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrimaryKey()
    {
        return $this->primary_key;
    }

    /**
     * Generated from protobuf field <code>repeated string primary_key = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrimaryKey($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->primary_key = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string defined_column = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDefinedColumn()
    {
        return $this->defined_column;
    }

    /**
     * Generated from protobuf field <code>repeated string defined_column = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDefinedColumn($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->defined_column = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.IndexUpdateMode index_update_mode = 4;</code>
     * @return int
     */
    public function getIndexUpdateMode()
    {
        return isset($this->index_update_mode) ? $this->index_update_mode : 0;
    }

    public function hasIndexUpdateMode()
    {
        return isset($this->index_update_mode);
    }

    public function clearIndexUpdateMode()
    {
        unset($this->index_update_mode);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.IndexUpdateMode index_update_mode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setIndexUpdateMode($var)
    {
        GPBUtil::checkEnum($var, \Protos\IndexUpdateMode::class);
        $this->index_update_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.IndexType index_type = 5;</code>
     * @return int
     */
    public function getIndexType()
    {
        return isset($this->index_type) ? $this->index_type : 0;
    }

    public function hasIndexType()
    {
        return isset($this->index_type);
    }

    public function clearIndexType()
    {
        unset($this->index_type);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.IndexType index_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setIndexType($var)
    {
        GPBUtil::checkEnum($var, \Protos\IndexType::class);
        $this->index_type = $var;

        return $this;
    }

}

