<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.table.PartitionRange</code>
 */
class PartitionRange extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required bytes begin = 1;</code>
     */
    protected $begin = null;
    /**
     * Generated from protobuf field <code>required bytes end = 2;</code>
     */
    protected $end = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $begin
     *     @type string $end
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\Table::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required bytes begin = 1;</code>
     * @return string
     */
    public function getBegin()
    {
        return isset($this->begin) ? $this->begin : '';
    }

    public function hasBegin()
    {
        return isset($this->begin);
    }

    public function clearBegin()
    {
        unset($this->begin);
    }

    /**
     * Generated from protobuf field <code>required bytes begin = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBegin($var)
    {
        GPBUtil::checkString($var, False);
        $this->begin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>required bytes end = 2;</code>
     * @return string
     */
    public function getEnd()
    {
        return isset($this->end) ? $this->end : '';
    }

    public function hasEnd()
    {
        return isset($this->end);
    }

    public function clearEnd()
    {
        unset($this->end);
    }

    /**
     * Generated from protobuf field <code>required bytes end = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEnd($var)
    {
        GPBUtil::checkString($var, False);
        $this->end = $var;

        return $this;
    }

}

