<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use UnexpectedValueException;

/**
 * Protobuf type <code>acs.tablestore.table.PrimaryKeyType</code>
 */
class PrimaryKeyType
{
    /**
     * Generated from protobuf enum <code>INTEGER = 1;</code>
     */
    const INTEGER = 1;
    /**
     * Generated from protobuf enum <code>STRING = 2;</code>
     */
    const STRING = 2;
    /**
     * Generated from protobuf enum <code>BINARY = 3;</code>
     */
    const BINARY = 3;

    private static $valueToName = [
        self::INTEGER => 'INTEGER',
        self::STRING => 'STRING',
        self::BINARY => 'BINARY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

