<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.table.ReservedThroughput</code>
 */
class ReservedThroughput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required .acs.tablestore.CapacityUnit capacity_unit = 1;</code>
     */
    protected $capacity_unit = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protos\CapacityUnit $capacity_unit
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\Table::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.CapacityUnit capacity_unit = 1;</code>
     * @return \Protos\CapacityUnit|null
     */
    public function getCapacityUnit()
    {
        return $this->capacity_unit;
    }

    public function hasCapacityUnit()
    {
        return isset($this->capacity_unit);
    }

    public function clearCapacityUnit()
    {
        unset($this->capacity_unit);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.CapacityUnit capacity_unit = 1;</code>
     * @param \Protos\CapacityUnit $var
     * @return $this
     */
    public function setCapacityUnit($var)
    {
        GPBUtil::checkMessage($var, \Protos\CapacityUnit::class);
        $this->capacity_unit = $var;

        return $this;
    }

}

