<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.table.ReservedThroughputDetails</code>
 */
class ReservedThroughputDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required .acs.tablestore.CapacityUnit capacity_unit = 1;</code>
     */
    protected $capacity_unit = null;
    /**
     * Generated from protobuf field <code>required int64 last_increase_time = 2;</code>
     */
    protected $last_increase_time = null;
    /**
     * Generated from protobuf field <code>optional int64 last_decrease_time = 3;</code>
     */
    protected $last_decrease_time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protos\CapacityUnit $capacity_unit
     *     @type int|string $last_increase_time
     *     @type int|string $last_decrease_time
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\Table::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.CapacityUnit capacity_unit = 1;</code>
     * @return \Protos\CapacityUnit|null
     */
    public function getCapacityUnit()
    {
        return $this->capacity_unit;
    }

    public function hasCapacityUnit()
    {
        return isset($this->capacity_unit);
    }

    public function clearCapacityUnit()
    {
        unset($this->capacity_unit);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.CapacityUnit capacity_unit = 1;</code>
     * @param \Protos\CapacityUnit $var
     * @return $this
     */
    public function setCapacityUnit($var)
    {
        GPBUtil::checkMessage($var, \Protos\CapacityUnit::class);
        $this->capacity_unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>required int64 last_increase_time = 2;</code>
     * @return int|string
     */
    public function getLastIncreaseTime()
    {
        return isset($this->last_increase_time) ? $this->last_increase_time : 0;
    }

    public function hasLastIncreaseTime()
    {
        return isset($this->last_increase_time);
    }

    public function clearLastIncreaseTime()
    {
        unset($this->last_increase_time);
    }

    /**
     * Generated from protobuf field <code>required int64 last_increase_time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastIncreaseTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_increase_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 last_decrease_time = 3;</code>
     * @return int|string
     */
    public function getLastDecreaseTime()
    {
        return isset($this->last_decrease_time) ? $this->last_decrease_time : 0;
    }

    public function hasLastDecreaseTime()
    {
        return isset($this->last_decrease_time);
    }

    public function clearLastDecreaseTime()
    {
        unset($this->last_decrease_time);
    }

    /**
     * Generated from protobuf field <code>optional int64 last_decrease_time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastDecreaseTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_decrease_time = $var;

        return $this;
    }

}

