<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/tablestore/row_single.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.row.single.ReturnContent</code>
 */
class ReturnContent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .acs.tablestore.row.single.ReturnType return_type = 1;</code>
     */
    protected $return_type = null;
    /**
     * Generated from protobuf field <code>repeated string return_column_names = 2;</code>
     */
    private $return_column_names;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $return_type
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $return_column_names
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\RowSingle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.row.single.ReturnType return_type = 1;</code>
     * @return int
     */
    public function getReturnType()
    {
        return isset($this->return_type) ? $this->return_type : 0;
    }

    public function hasReturnType()
    {
        return isset($this->return_type);
    }

    public function clearReturnType()
    {
        unset($this->return_type);
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.row.single.ReturnType return_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setReturnType($var)
    {
        GPBUtil::checkEnum($var, \Protos\ReturnType::class);
        $this->return_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string return_column_names = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReturnColumnNames()
    {
        return $this->return_column_names;
    }

    /**
     * Generated from protobuf field <code>repeated string return_column_names = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReturnColumnNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->return_column_names = $arr;

        return $this;
    }

}

