<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/tablestore/row_single.proto

namespace Protos;

use UnexpectedValueException;

/**
 * Protobuf type <code>acs.tablestore.row.single.ReturnType</code>
 */
class ReturnType
{
    /**
     * Generated from protobuf enum <code>RT_NONE = 0;</code>
     */
    const RT_NONE = 0;
    /**
     * Generated from protobuf enum <code>RT_PK = 1;</code>
     */
    const RT_PK = 1;
    /**
     * Generated from protobuf enum <code>RT_AFTER_MODIFY = 2;</code>
     */
    const RT_AFTER_MODIFY = 2;

    private static $valueToName = [
        self::RT_NONE => 'RT_NONE',
        self::RT_PK => 'RT_PK',
        self::RT_AFTER_MODIFY => 'RT_AFTER_MODIFY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

