<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: row_batch.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.row.batch.RowInBatchWriteRowResponse</code>
 */
class RowInBatchWriteRowResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required bool is_ok = 1 [default = true];</code>
     */
    protected $is_ok = null;
    /**
     * Generated from protobuf field <code>optional .acs.tablestore.Error error = 2;</code>
     */
    protected $error = null;
    /**
     * Generated from protobuf field <code>optional .acs.tablestore.row.ConsumedCapacity consumed = 3;</code>
     */
    protected $consumed = null;
    /**
     * Generated from protobuf field <code>optional bytes row = 4;</code>
     */
    protected $row = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_ok
     *     @type \Protos\Error $error
     *     @type \Protos\ConsumedCapacity $consumed
     *     @type string $row
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\RowBatch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required bool is_ok = 1 [default = true];</code>
     * @return bool
     */
    public function getIsOk()
    {
        return isset($this->is_ok) ? $this->is_ok : false;
    }

    public function hasIsOk()
    {
        return isset($this->is_ok);
    }

    public function clearIsOk()
    {
        unset($this->is_ok);
    }

    /**
     * Generated from protobuf field <code>required bool is_ok = 1 [default = true];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsOk($var)
    {
        GPBUtil::checkBool($var);
        $this->is_ok = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.Error error = 2;</code>
     * @return \Protos\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.Error error = 2;</code>
     * @param \Protos\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Protos\Error::class);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.row.ConsumedCapacity consumed = 3;</code>
     * @return \Protos\ConsumedCapacity|null
     */
    public function getConsumed()
    {
        return $this->consumed;
    }

    public function hasConsumed()
    {
        return isset($this->consumed);
    }

    public function clearConsumed()
    {
        unset($this->consumed);
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.row.ConsumedCapacity consumed = 3;</code>
     * @param \Protos\ConsumedCapacity $var
     * @return $this
     */
    public function setConsumed($var)
    {
        GPBUtil::checkMessage($var, \Protos\ConsumedCapacity::class);
        $this->consumed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes row = 4;</code>
     * @return string
     */
    public function getRow()
    {
        return isset($this->row) ? $this->row : '';
    }

    public function hasRow()
    {
        return isset($this->row);
    }

    public function clearRow()
    {
        unset($this->row);
    }

    /**
     * Generated from protobuf field <code>optional bytes row = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRow($var)
    {
        GPBUtil::checkString($var, False);
        $this->row = $var;

        return $this;
    }

}

