<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.table.StreamDetails</code>
 */
class StreamDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required bool enable_stream = 1;</code>
     */
    protected $enable_stream = null;
    /**
     * Generated from protobuf field <code>optional string stream_id = 2;</code>
     */
    protected $stream_id = null;
    /**
     * Generated from protobuf field <code>optional int32 expiration_time = 3;</code>
     */
    protected $expiration_time = null;
    /**
     * Generated from protobuf field <code>optional int64 last_enable_time = 4;</code>
     */
    protected $last_enable_time = null;
    /**
     * Generated from protobuf field <code>repeated string column_to_get = 5;</code>
     */
    private $column_to_get;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enable_stream
     *     @type string $stream_id
     *     @type int $expiration_time
     *     @type int|string $last_enable_time
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $column_to_get
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\Table::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required bool enable_stream = 1;</code>
     * @return bool
     */
    public function getEnableStream()
    {
        return isset($this->enable_stream) ? $this->enable_stream : false;
    }

    public function hasEnableStream()
    {
        return isset($this->enable_stream);
    }

    public function clearEnableStream()
    {
        unset($this->enable_stream);
    }

    /**
     * Generated from protobuf field <code>required bool enable_stream = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableStream($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_stream = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string stream_id = 2;</code>
     * @return string
     */
    public function getStreamId()
    {
        return isset($this->stream_id) ? $this->stream_id : '';
    }

    public function hasStreamId()
    {
        return isset($this->stream_id);
    }

    public function clearStreamId()
    {
        unset($this->stream_id);
    }

    /**
     * Generated from protobuf field <code>optional string stream_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 expiration_time = 3;</code>
     * @return int
     */
    public function getExpirationTime()
    {
        return isset($this->expiration_time) ? $this->expiration_time : 0;
    }

    public function hasExpirationTime()
    {
        return isset($this->expiration_time);
    }

    public function clearExpirationTime()
    {
        unset($this->expiration_time);
    }

    /**
     * Generated from protobuf field <code>optional int32 expiration_time = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setExpirationTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->expiration_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 last_enable_time = 4;</code>
     * @return int|string
     */
    public function getLastEnableTime()
    {
        return isset($this->last_enable_time) ? $this->last_enable_time : 0;
    }

    public function hasLastEnableTime()
    {
        return isset($this->last_enable_time);
    }

    public function clearLastEnableTime()
    {
        unset($this->last_enable_time);
    }

    /**
     * Generated from protobuf field <code>optional int64 last_enable_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastEnableTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_enable_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string column_to_get = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumnToGet()
    {
        return $this->column_to_get;
    }

    /**
     * Generated from protobuf field <code>repeated string column_to_get = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumnToGet($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->column_to_get = $arr;

        return $this;
    }

}

