<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.table.TableOptions</code>
 */
class TableOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 time_to_live = 1;</code>
     */
    protected $time_to_live = null;
    /**
     * Generated from protobuf field <code>optional int32 max_versions = 2;</code>
     */
    protected $max_versions = null;
    /**
     * Generated from protobuf field <code>optional int64 deviation_cell_version_in_sec = 5;</code>
     */
    protected $deviation_cell_version_in_sec = null;
    /**
     * Generated from protobuf field <code>optional bool allow_update = 6;</code>
     */
    protected $allow_update = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $time_to_live
     *     @type int $max_versions
     *     @type int|string $deviation_cell_version_in_sec
     *     @type bool $allow_update
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\Table::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 time_to_live = 1;</code>
     * @return int
     */
    public function getTimeToLive()
    {
        return isset($this->time_to_live) ? $this->time_to_live : 0;
    }

    public function hasTimeToLive()
    {
        return isset($this->time_to_live);
    }

    public function clearTimeToLive()
    {
        unset($this->time_to_live);
    }

    /**
     * Generated from protobuf field <code>optional int32 time_to_live = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeToLive($var)
    {
        GPBUtil::checkInt32($var);
        $this->time_to_live = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 max_versions = 2;</code>
     * @return int
     */
    public function getMaxVersions()
    {
        return isset($this->max_versions) ? $this->max_versions : 0;
    }

    public function hasMaxVersions()
    {
        return isset($this->max_versions);
    }

    public function clearMaxVersions()
    {
        unset($this->max_versions);
    }

    /**
     * Generated from protobuf field <code>optional int32 max_versions = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxVersions($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_versions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 deviation_cell_version_in_sec = 5;</code>
     * @return int|string
     */
    public function getDeviationCellVersionInSec()
    {
        return isset($this->deviation_cell_version_in_sec) ? $this->deviation_cell_version_in_sec : 0;
    }

    public function hasDeviationCellVersionInSec()
    {
        return isset($this->deviation_cell_version_in_sec);
    }

    public function clearDeviationCellVersionInSec()
    {
        unset($this->deviation_cell_version_in_sec);
    }

    /**
     * Generated from protobuf field <code>optional int64 deviation_cell_version_in_sec = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeviationCellVersionInSec($var)
    {
        GPBUtil::checkInt64($var);
        $this->deviation_cell_version_in_sec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool allow_update = 6;</code>
     * @return bool
     */
    public function getAllowUpdate()
    {
        return isset($this->allow_update) ? $this->allow_update : false;
    }

    public function hasAllowUpdate()
    {
        return isset($this->allow_update);
    }

    public function clearAllowUpdate()
    {
        unset($this->allow_update);
    }

    /**
     * Generated from protobuf field <code>optional bool allow_update = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowUpdate($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_update = $var;

        return $this;
    }

}

