<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: row_batch.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.row.batch.TableInBatchWriteRowResponse</code>
 */
class TableInBatchWriteRowResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     */
    protected $table_name = null;
    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.row.batch.RowInBatchWriteRowResponse put_rows = 2;</code>
     */
    private $put_rows;
    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.row.batch.RowInBatchWriteRowResponse update_rows = 3;</code>
     */
    private $update_rows;
    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.row.batch.RowInBatchWriteRowResponse delete_rows = 4;</code>
     */
    private $delete_rows;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $table_name
     *     @type array<\Protos\RowInBatchWriteRowResponse>|\Google\Protobuf\Internal\RepeatedField $put_rows
     *     @type array<\Protos\RowInBatchWriteRowResponse>|\Google\Protobuf\Internal\RepeatedField $update_rows
     *     @type array<\Protos\RowInBatchWriteRowResponse>|\Google\Protobuf\Internal\RepeatedField $delete_rows
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\RowBatch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return isset($this->table_name) ? $this->table_name : '';
    }

    public function hasTableName()
    {
        return isset($this->table_name);
    }

    public function clearTableName()
    {
        unset($this->table_name);
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.row.batch.RowInBatchWriteRowResponse put_rows = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPutRows()
    {
        return $this->put_rows;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.row.batch.RowInBatchWriteRowResponse put_rows = 2;</code>
     * @param array<\Protos\RowInBatchWriteRowResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPutRows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\RowInBatchWriteRowResponse::class);
        $this->put_rows = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.row.batch.RowInBatchWriteRowResponse update_rows = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUpdateRows()
    {
        return $this->update_rows;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.row.batch.RowInBatchWriteRowResponse update_rows = 3;</code>
     * @param array<\Protos\RowInBatchWriteRowResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUpdateRows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\RowInBatchWriteRowResponse::class);
        $this->update_rows = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.row.batch.RowInBatchWriteRowResponse delete_rows = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeleteRows()
    {
        return $this->delete_rows;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.row.batch.RowInBatchWriteRowResponse delete_rows = 4;</code>
     * @param array<\Protos\RowInBatchWriteRowResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeleteRows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\RowInBatchWriteRowResponse::class);
        $this->delete_rows = $arr;

        return $this;
    }

}

