<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.table.TableMeta</code>
 */
class TableMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     */
    protected $table_name = null;
    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.table.PrimaryKeySchema primary_key = 2;</code>
     */
    private $primary_key;
    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.table.DefinedColumnSchema defined_column = 3;</code>
     */
    private $defined_column;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $table_name
     *     @type array<\Protos\PrimaryKeySchema>|\Google\Protobuf\Internal\RepeatedField $primary_key
     *     @type array<\Protos\DefinedColumnSchema>|\Google\Protobuf\Internal\RepeatedField $defined_column
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\Table::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return isset($this->table_name) ? $this->table_name : '';
    }

    public function hasTableName()
    {
        return isset($this->table_name);
    }

    public function clearTableName()
    {
        unset($this->table_name);
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.table.PrimaryKeySchema primary_key = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrimaryKey()
    {
        return $this->primary_key;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.table.PrimaryKeySchema primary_key = 2;</code>
     * @param array<\Protos\PrimaryKeySchema>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrimaryKey($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\PrimaryKeySchema::class);
        $this->primary_key = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.table.DefinedColumnSchema defined_column = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDefinedColumn()
    {
        return $this->defined_column;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.tablestore.table.DefinedColumnSchema defined_column = 3;</code>
     * @param array<\Protos\DefinedColumnSchema>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDefinedColumn($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\DefinedColumnSchema::class);
        $this->defined_column = $arr;

        return $this;
    }

}

