<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.table.UpdateTableRequest</code>
 */
class UpdateTableRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     */
    protected $table_name = null;
    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.ReservedThroughput reserved_throughput = 2;</code>
     */
    protected $reserved_throughput = null;
    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.TableOptions table_options = 3;</code>
     */
    protected $table_options = null;
    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.StreamSpecification stream_spec = 4;</code>
     */
    protected $stream_spec = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $table_name
     *     @type \Protos\ReservedThroughput $reserved_throughput
     *     @type \Protos\TableOptions $table_options
     *     @type \Protos\StreamSpecification $stream_spec
     * }
     */
    public function __construct($data = NULL) {
        \Protos\Metadata\Table::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return isset($this->table_name) ? $this->table_name : '';
    }

    public function hasTableName()
    {
        return isset($this->table_name);
    }

    public function clearTableName()
    {
        unset($this->table_name);
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.ReservedThroughput reserved_throughput = 2;</code>
     * @return \Protos\ReservedThroughput|null
     */
    public function getReservedThroughput()
    {
        return $this->reserved_throughput;
    }

    public function hasReservedThroughput()
    {
        return isset($this->reserved_throughput);
    }

    public function clearReservedThroughput()
    {
        unset($this->reserved_throughput);
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.ReservedThroughput reserved_throughput = 2;</code>
     * @param \Protos\ReservedThroughput $var
     * @return $this
     */
    public function setReservedThroughput($var)
    {
        GPBUtil::checkMessage($var, \Protos\ReservedThroughput::class);
        $this->reserved_throughput = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.TableOptions table_options = 3;</code>
     * @return \Protos\TableOptions|null
     */
    public function getTableOptions()
    {
        return $this->table_options;
    }

    public function hasTableOptions()
    {
        return isset($this->table_options);
    }

    public function clearTableOptions()
    {
        unset($this->table_options);
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.TableOptions table_options = 3;</code>
     * @param \Protos\TableOptions $var
     * @return $this
     */
    public function setTableOptions($var)
    {
        GPBUtil::checkMessage($var, \Protos\TableOptions::class);
        $this->table_options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.StreamSpecification stream_spec = 4;</code>
     * @return \Protos\StreamSpecification|null
     */
    public function getStreamSpec()
    {
        return $this->stream_spec;
    }

    public function hasStreamSpec()
    {
        return isset($this->stream_spec);
    }

    public function clearStreamSpec()
    {
        unset($this->stream_spec);
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.StreamSpecification stream_spec = 4;</code>
     * @param \Protos\StreamSpecification $var
     * @return $this
     */
    public function setStreamSpec($var)
    {
        GPBUtil::checkMessage($var, \Protos\StreamSpecification::class);
        $this->stream_spec = $var;

        return $this;
    }

}

