name: Run Tests

on:
  push:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress --ansi

      - name: Execute Tests
        run: composer test:unit

  integration:
    runs-on: ubuntu-latest

    concurrency:
      group: integration

    name: Integration Test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer update --prefer-stable --no-interaction --no-progress --ansi

      - name: Run Integration Test
        run: composer test:integration
        env:
          INTEGRATION_TEST_ENABLED: true
          ACS_ACCESS_KEY_ID: ${{ secrets.ACS_ACCESS_KEY_ID }}
          ACS_ACCESS_KEY_SECRET: ${{ secrets.ACS_ACCESS_KEY_SECRET }}
          TS_ENDPOINT: ${{ secrets.TS_ENDPOINT }}
          TS_INSTANCE: ${{ secrets.TS_INSTANCE }}
