name: Static Analysis

on:
  push:
  pull_request:

jobs:
  static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer update --prefer-stable --no-interaction --no-progress --ansi

      - name: Run Style Checks
        run: composer test:style

      - name: Run Refactor Checks
        run: composer test:refactor

      - name: Run Lint Checks
        run: composer test:static
